### ISSUE TITLE
Namespace should be applied to all YAML files

### ISSUE THREAD

**Issue by d7oc** [owncloud/ocis-charts#358] opened 2023-07-12 09:26 UTC
I've just detected that the namespace value is not applied to all YAML files. It only exists in the following ones

<details> <summary> `grep -rl "ocis.namespace" * |grep "charts/ocis/templates"|sort` </summary>

```
charts/ocis/templates/_common/_tplvalues.tpl
charts/ocis/templates/_common/ocis-service-registry/clusterrole.yaml
charts/ocis/templates/_common/ocis-service-registry/rolebinding.yaml
charts/ocis/templates/antivirus/service.yaml
charts/ocis/templates/appprovider/service.yaml
charts/ocis/templates/appregistry/config.yaml
charts/ocis/templates/appregistry/service.yaml
charts/ocis/templates/audit/service.yaml
charts/ocis/templates/authbasic/service.yaml
charts/ocis/templates/authmachine/service.yaml
charts/ocis/templates/eventhistory/service.yaml
charts/ocis/templates/frontend/service.yaml
charts/ocis/templates/gateway/service.yaml
charts/ocis/templates/graph/service.yaml
charts/ocis/templates/groups/service.yaml
charts/ocis/templates/idm/pvc.yaml
charts/ocis/templates/idm/service.yaml
charts/ocis/templates/idp/service.yaml
charts/ocis/templates/monitoring/servicemonitor.yaml
charts/ocis/templates/nats/pvc.yaml
charts/ocis/templates/nats/service.yaml
charts/ocis/templates/notifications/service.yaml
charts/ocis/templates/ocdav/service.yaml
charts/ocis/templates/ocs/service.yaml
charts/ocis/templates/policies/config.yaml
charts/ocis/templates/policies/deployment.yaml
charts/ocis/templates/policies/service.yaml
charts/ocis/templates/postprocessing/service.yaml
charts/ocis/templates/proxy/config.yaml
charts/ocis/templates/proxy/service.yaml
charts/ocis/templates/search/pvc.yaml
charts/ocis/templates/search/service.yaml
charts/ocis/templates/settings/config.yaml
charts/ocis/templates/settings/service.yaml
charts/ocis/templates/sharing/service.yaml
charts/ocis/templates/storagepubliclink/service.yaml
charts/ocis/templates/storageshares/service.yaml
charts/ocis/templates/storagesystem/pvc.yaml
charts/ocis/templates/storagesystem/service.yaml
charts/ocis/templates/storageusers/jobs.yaml
charts/ocis/templates/storageusers/pvc.yaml
charts/ocis/templates/storageusers/service.yaml
charts/ocis/templates/store/pvc.yaml
charts/ocis/templates/store/service.yaml
charts/ocis/templates/thumbnails/jobs.yaml
charts/ocis/templates/thumbnails/pvc.yaml
charts/ocis/templates/thumbnails/service.yaml
charts/ocis/templates/userlog/service.yaml
charts/ocis/templates/users/service.yaml
charts/ocis/templates/web/config.yaml
charts/ocis/templates/web/pvc.yaml
charts/ocis/templates/web/service.yaml
charts/ocis/templates/webdav/service.yaml
```

</details>

So the following ones are missing:

<details> <summary> `grep -rL "ocis.namespace" * |grep "charts/ocis/templates"|sort` </summary>

```
charts/ocis/templates/NOTES.txt
charts/ocis/templates/_common/_configvalues.tpl
charts/ocis/templates/_common/hpa.tpl
charts/ocis/templates/_common/labels/labels.tpl
charts/ocis/templates/_common/ocis-service-registry/README.md
charts/ocis/templates/antivirus/deployment.yaml
charts/ocis/templates/antivirus/hpa.yaml
charts/ocis/templates/antivirus/pdb.yaml
charts/ocis/templates/appprovider/deployment.yaml
charts/ocis/templates/appregistry/deployment.yaml
charts/ocis/templates/audit/deployment.yaml
charts/ocis/templates/audit/hpa.yaml
charts/ocis/templates/audit/pdb.yaml
charts/ocis/templates/authbasic/deployment.yaml
charts/ocis/templates/authbasic/hpa.yaml
charts/ocis/templates/authbasic/pdb.yaml
charts/ocis/templates/authmachine/deployment.yaml
charts/ocis/templates/authmachine/hpa.yaml
charts/ocis/templates/authmachine/pdb.yaml
charts/ocis/templates/authmachine/secret.yaml
charts/ocis/templates/eventhistory/deployment.yaml
charts/ocis/templates/eventhistory/hpa.yaml
charts/ocis/templates/eventhistory/pdb.yaml
charts/ocis/templates/extra-resources.yaml
charts/ocis/templates/frontend/deployment.yaml
charts/ocis/templates/frontend/hpa.yaml
charts/ocis/templates/frontend/pdb.yaml
charts/ocis/templates/gateway/deployment.yaml
charts/ocis/templates/gateway/hpa.yaml
charts/ocis/templates/gateway/pdb.yaml
charts/ocis/templates/graph/configmap.yaml
charts/ocis/templates/graph/deployment.yaml
charts/ocis/templates/graph/hpa.yaml
charts/ocis/templates/graph/pdb.yaml
charts/ocis/templates/groups/deployment.yaml
charts/ocis/templates/groups/hpa.yaml
charts/ocis/templates/groups/pdb.yaml
charts/ocis/templates/idm/deployment.yaml
charts/ocis/templates/idm/secret.yaml
charts/ocis/templates/idp/deployment.yaml
charts/ocis/templates/idp/secret.yaml
charts/ocis/templates/nats/deployment.yaml
charts/ocis/templates/notifications/deployment.yaml
charts/ocis/templates/notifications/hpa.yaml
charts/ocis/templates/notifications/pdb.yaml
charts/ocis/templates/ocdav/deployment.yaml
charts/ocis/templates/ocdav/hpa.yaml
charts/ocis/templates/ocdav/pdb.yaml
charts/ocis/templates/ocs/deployment.yaml
charts/ocis/templates/ocs/hpa.yaml
charts/ocis/templates/ocs/pdb.yaml
charts/ocis/templates/policies/hpa.yaml
charts/ocis/templates/policies/pdb.yaml
charts/ocis/templates/postprocessing/deployment.yaml
charts/ocis/templates/postprocessing/hpa.yaml
charts/ocis/templates/postprocessing/pdb.yaml
charts/ocis/templates/proxy/deployment.yaml
charts/ocis/templates/proxy/hpa.yaml
charts/ocis/templates/proxy/ingress.yaml
charts/ocis/templates/proxy/pdb.yaml
charts/ocis/templates/search/deployment.yaml
charts/ocis/templates/settings/deployment.yaml
charts/ocis/templates/settings/hpa.yaml
charts/ocis/templates/settings/pdb.yaml
charts/ocis/templates/sharing/deployment.yaml
charts/ocis/templates/sharing/hpa.yaml
charts/ocis/templates/sharing/pdb.yaml
charts/ocis/templates/storagepubliclink/deployment.yaml
charts/ocis/templates/storagepubliclink/hpa.yaml
charts/ocis/templates/storagepubliclink/pdb.yaml
charts/ocis/templates/storageshares/deployment.yaml
charts/ocis/templates/storageshares/hpa.yaml
charts/ocis/templates/storageshares/pdb.yaml
charts/ocis/templates/storagesystem/deployment.yaml
charts/ocis/templates/storagesystem/hpa.yaml
charts/ocis/templates/storagesystem/pdb.yaml
charts/ocis/templates/storagesystem/secret.yaml
charts/ocis/templates/storageusers/configmap.yaml
charts/ocis/templates/storageusers/deployment.yaml
charts/ocis/templates/storageusers/hpa.yaml
charts/ocis/templates/storageusers/pdb.yaml
charts/ocis/templates/storageusers/secret.yaml
charts/ocis/templates/store/deployment.yaml
charts/ocis/templates/thumbnails/deployment.yaml
charts/ocis/templates/thumbnails/hpa.yaml
charts/ocis/templates/thumbnails/pdb.yaml
charts/ocis/templates/thumbnails/secret.yaml
charts/ocis/templates/userlog/deployment.yaml
charts/ocis/templates/userlog/hpa.yaml
charts/ocis/templates/userlog/pdb.yaml
charts/ocis/templates/users/deployment.yaml
charts/ocis/templates/users/hpa.yaml
charts/ocis/templates/users/pdb.yaml
charts/ocis/templates/web/deployment.yaml
charts/ocis/templates/web/hpa.yaml
charts/ocis/templates/web/pdb.yaml
charts/ocis/templates/webdav/deployment.yaml
charts/ocis/templates/webdav/hpa.yaml
charts/ocis/templates/webdav/pdb.yaml
```

</details>

**Comment by wkloucek** [comment] 2023-07-12 09:57
closing as duplicate of https://github.com/owncloud/ocis-charts/issues/353

**Closed by wkloucek** 2023-07-12 09:57 UTC
